### ISSUE TITLE
Failed to load the autocomplete-bibtex package

### ISSUE THREAD

**Issue by akrawitz** [apcshields/autocomplete-bibtex#107]
Try to do a fresh install of `autocomplete-bibtex`.
It fails with the error message:
`Failed to load the autocomplete-bibtex package`
Within the stack trace the error is:
`Error: Cannot find module './ts-compiled/command-aliases'`
See below for the full stack trace.

The problem seems to be that the dependency `latex-to-unicode-converter` has been deprecated, and the owner of that package has removed necessary files in the last few days from recent versions - thus leading to the missing module error.

It looks like the quickest fix would be to change the dependency in the package.json file to require a specific working version. Instead of:
`"latex-to-unicode-converter": "^0.5.2",`
use:
`"latex-to-unicode-converter": "0.5.2",`

Presumably in the long run, a replacement would need to be found, or someone would need to revive the package.

Thanks,
Adam

**Stack trace** (I've replaced the user name in the file paths)
```
Error: Cannot find module './ts-compiled/command-aliases'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:154765)
    at Module.require (file:///C:/Users/Xxx%20Yyy/AppData/Local/atom/app-1.37.0/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:146072)
    at Object.<anonymous> (C:\Users\Xxx Yyy\.atom\packages\autocomplete-bibtex\node_modules\latex-to-unicode-converter\index.js:6:10)
    at Object.<anonymous> (C:\Users\Xxx Yyy\.atom\packages\autocomplete-bibtex\node_modules\latex-to-unicode-converter\index.js:17:3)
    at Module.get_Module._compile (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:146782)
    at Object.value [as .js] (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Xxx%20Yyy/AppData/Local/atom/app-1.37.0/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:146072)
    at Object.<anonymous> (C:\Users\Xxx Yyy\.atom\packages\autocomplete-bibtex\lib\lite-bibtex-parse.js:36:32)
    at Object.<anonymous> (file:///C:/Users/Xxx Yyy/.atom/packages/autocomplete-bibtex/lib/lite-bibtex-parse.js:526:40)
    at Module.get_Module._compile (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:146782)
    at Object.value [as .js] (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Xxx%20Yyy/AppData/Local/atom/app-1.37.0/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:146072)
    at Object.<anonymous> (file:///C:/Users/Xxx Yyy/.atom/packages/autocomplete-bibtex/lib/bibtex-reader.js:5:21)
    at Object.<anonymous> (file:///C:/Users/Xxx Yyy/.atom/packages/autocomplete-bibtex/lib/bibtex-reader.js:10:34)
    at Module.get_Module._compile (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:146782)
    at Object.value [as .js] (C:\Users\Xxx Yyy\AppData\Local\atom\app-1.37.0\resources\app\static\<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

**Versions**
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by mangecoeur** [comment]
pr accepted

**Comment by akrawitz** [comment]
Thanks!

**Comment by Alex-Linhares** [comment]
Same issue here. 

Cannot find module './ts-compiled/command-aliases'
Hide Stack Trace
Error: Cannot find module './ts-compiled/command-aliases'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155413)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/node_modules/latex-to-unicode-converter/index.js:6:10)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/node_modules/latex-to-unicode-converter/index.js:17:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/lib/lite-bibtex-parse.js:36:32)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/lib/lite-bibtex-parse.js:526:40)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/lib/bibtex-reader.js:5:21)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/lib/bibtex-reader.js:10:34)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/lib/provider.js:8:22)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/lib/provider.js:37:39)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/lib/main.js:6:27)
    at Object.<anonymous> (/home/username/.atom/packages/autocomplete-bibtex/lib/main.js:98:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:688211)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3218243)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3204783)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3203615)
    at Package.load (/usr/share/atom/resources/app/static/<embedded>:11:3204356)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/static/<embedded>:11:381128)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/static/<embedded>:11:379856)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382428)
    at /home/username/.atom/packages/sync-settings/lib/package-manager.coffee:167:25
    at exit (/home/username/.atom/packages/sync-settings/lib/package-manager.coffee:27:7)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1128169)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1128323)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1126925)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
