### ISSUE TITLE
Failed to load the latex package

### ISSUE THREAD

**Issue by tgouhier** [apcshields/autocomplete-bibtex#22]
I updated Atom to version 0.198.0 and it generated the following error with the autocomplete-bibtex package:

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package, v0.5.7

### Stack Trace

Failed to load the latex package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/tarik/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6126:12
    at Array.forEach (native)
    at extend.keys (/Users/tarik/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6125:12)
    at /Users/tarik/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:179:25
    at Array.map (native)
    at Array.<anonymous> (/Users/tarik/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:180:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/babel/traversal/scope.js:884:121
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/babel/traversal/scope.js:893:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "markdown-preview-katex",
      "sort-lines",
      "switch-header-source",
      "autocomplete-plus",
      "deprecation-cop"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.5.7
language-knitr, v0.1.0
language-latex, v0.6.1
language-matlab, v0.1.0
language-r, v0.2.0
latex, v0.23.1
markdown-preview-plus, v1.4.0
minimap, v4.8.0
monokai, v0.14.0
texlicious, v0.4.1

# Dev
No dev packages
```

**Comment by jfsantos** [comment]
Same here on Linux with Atom 0.206.0.

**Comment by isezen** [comment]
Same on Mac OS X 10.10.3 with Atom 0.208.0

**Comment by pymk** [comment]
Same issue on Mac OS X 10.10.3 with Atom 0.210.0.

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "material"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-bibtex, v0.5.7
language-latex, v0.6.1
latex, v0.24.2
material, v2.1.4

# Dev
No dev packages
```

**Comment by swaroopjcse** [comment]
Same issue with Mac OS X 10.10.3, Atom 1.0.0
##### Config
```
core:
    themes: [
      "atom-light-ui"
      "atom-light-syntax"
    ]
```
##### Packages
```
autocomplete-bibtex, v0.5.7
language-latex, v0.6.1
latex, v0.24.2
```

**Comment by daiyuxiao** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.11
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package, v0.5.7


### Stack Trace

Failed to load the latex package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/mac/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6126:12
    at Array.forEach (native)
    at extend.keys (/Users/mac/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6125:12)
    at /Users/mac/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:179:25
    at Array.map (native)
    at Array.<anonymous> (/Users/mac/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:180:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/babel/traversal/scope/index.js:1029:132
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/babel/traversal/scope/index.js:1038:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "iTunes",
      "iTunes",
      "iTunes",
      "terminal-status"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
auto-update-packages, v1.0.0
autocomplete-bibtex, v0.5.7
language-latex, v0.6.1
latex, v0.25.0
latex-completions, v0.3.0
pdf-view, v0.22.0
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by apcshields** [comment]
@jfsantos, @isezen, @pymk, @swaroopjcse,

v0.6.0, released today, is expected to fix this issue. Could you please update and test?

Thanks!
Andrew

**Comment by swaroopjcse** [comment]
Thanks, Andrew. That update seems to have fixed the issue.

**Comment by isezen** [comment]
Atom 1.0.3 & MacOSX 10.10.4 seems fixed. Thanks.

**Comment by apcshields** [comment]
@swaroopjcse, @isezen,

Sure! Thank @mangecoeur, who coded the solution!
