### ISSUE TITLE
Failed to load the autocomplete-modules package

### ISSUE THREAD

**Issue by jhopper28** [apcshields/autocomplete-bibtex#23]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package, v0.5.7
### Stack Trace

Failed to load the autocomplete-modules package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/Jeff/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6126:12
    at Array.forEach (native)
    at extend.keys (/Users/Jeff/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6125:12)
    at /Users/Jeff/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:179:25
    at Array.map (native)
    at Array.<anonymous> (/Users/Jeff/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:180:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/babel/traversal/scope.js:884:121
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/babel/traversal/scope.js:893:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/Jeff/Projects",
    "disabledPackages": [
      "terminal-status",
      "language-javascript-jsx"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
angularjs, v0.1.0
atom-color-highlight, v3.0.9
atom-jsx-transform, v0.1.0
atom-typescript, v4.2.0
autocomplete-bibtex, v0.5.7
autocomplete-css, v0.7.2
autocomplete-html, v0.7.1
autocomplete-modules, v0.3.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.13.1
browser-refresh, v0.8.3
build, v0.30.0
color-picker, v1.7.0
docblockr, v0.6.3
git-projects, v1.13.0
highlight-selected, v0.9.2
language-swift, v0.4.0
linter, v0.12.2
minimap, v4.8.0
react, v0.11.8
react-snippets, v0.1.4
regex-railroad-diagram, v0.7.4
save-session, v0.13.5
slash-closer, v0.7.1
svg-preview, v0.5.1
tab-history, v0.4.0

# Dev
No dev packages
```

**Comment by winnieXY** [comment]
I can reproduce this problem. Are any logs needed to get this fixed?

**Comment by apcshields** [comment]
winnieXY,

I don’t they could hurt. I haven’t been able to reproduce it yet.

Thanks,
Andrew

**Comment by winnieXY** [comment]
How can I generate a most useable debug log?

**Comment by ForNeVeR** [comment]
I have the same on Windows 7, atom 1.0.2. The error message pops up right after I start atom.

**Comment by ForNeVeR** [comment]
It seems to be incompatibility with the minimap package. I find it suspicious that every reporter (see also #26, #32) have the same minimap package installed.

**Comment by apcshields** [comment]
@jhopper28, @winnieXY, @ForNeVeR,

v0.6.0, released today, is expected to fix this issue. Could you please update and test?

Thanks!
Andrew
