### ISSUE TITLE
Failed to load the data-atom package

### ISSUE THREAD

**Issue by mogaio** [apcshields/autocomplete-bibtex#26]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package, v0.5.7
### Stack Trace

Failed to load the data-atom package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/Home/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6126:12
    at Array.forEach (native)
    at extend.keys (/Users/Home/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6125:12)
    at /Users/Home/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:179:25
    at Array.map (native)
    at Array.<anonymous> (/Users/Home/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:180:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/babel/traversal/scope/index.js:1029:132
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/babel/traversal/scope/index.js:1038:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-bibtex, v0.5.7
color-picker, v2.0.10
data-atom, v0.6.1
jsformat, v0.9.0
language-rdf, v0.2.0
linter, v1.2.3
minimap, v4.11.2
pretty-json, v0.4.1
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by apcshields** [comment]
@mogaio,

v0.6.0, released today, is expected to fix this issue. Could you please update and test?

Thanks!
Andrew
