### ISSUE TITLE
Failed to load the minimap-linter package

### ISSUE THREAD

**Issue by ritashugisha** [apcshields/autocomplete-bibtex#32]
[Enter steps to reproduce below:]

1. Updated to Atom 1.0.3
2. Thrown on startup

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.1
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package, v0.5.7

### Stack Trace

Failed to load the minimap-linter package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/ritashugisha/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6126:12
    at Array.forEach (native)
    at extend.keys (/Users/ritashugisha/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:6125:12)
    at /Users/ritashugisha/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:179:25
    at Array.map (native)
    at Array.<anonymous> (/Users/ritashugisha/.atom/packages/autocomplete-bibtex/node_modules/sugar/release/sugar-full.development.js:180:23)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/traversal/scope/index.js:1136:132
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/lib/traversal/scope/index.js:1149:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "rampart-syntax"
    ],
    "projectHome": "/Users/ritashugisha/Documents/GitHub",
    "disabledPackages": [
      "linter-flake8",
      "linter-pep257",
      "pane-manager",
      "minimap",
      "pigments"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.9
atom-runner, v2.4.1
auto-indent, v0.5.0
autocomplete-bibtex, v0.5.7
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.3
browser-plus, v0.0.30
color-picker, v2.0.11
file-icons, v1.5.8
hex, v0.6.2
language-latex, v0.6.1
latex, v0.25.0
latexer, v0.2.4
linter, v1.2.4
linter-coffeelint, v1.0.0
linter-pep8, v1.0.1
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-linter, v1.0.0
pdf-view, v0.23.0
project-manager, v1.15.11
rampart-syntax, v0.0.0
remote-edit, v1.8.14
revert-buffer, v0.5.0
tabs-to-spaces, v0.11.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by apcshields** [comment]
@ritashugisha,

v0.6.0, released today, is expected to fix this issue. Could you please update and test?

Thanks!
Andrew

**Comment by ritashugisha** [comment]
Error is no longer thrown on startup. Thanks for the quick resolution!

**Comment by apcshields** [comment]
No problem! Thank @mangecoeur, who coded the solution!
