### ISSUE TITLE
Failed to load the linter-jscs package

### ISSUE THREAD

**Issue by tvanantwerp** [apcshields/autocomplete-bibtex#33]
[Enter steps to reproduce below:]

1. Happens immediately on opening Atom

**Atom Version**: 1.0.3
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package, v0.5.7

### Stack Trace

Failed to load the linter-jscs package

```
At undefined is not a function

TypeError: undefined is not a function
    at C:\Users\tva\.atom\packages\autocomplete-bibtex\node_modules\sugar\release\sugar-full.development.js:6126:12
    at Array.forEach (native)
    at extend.keys (C:\Users\tva\.atom\packages\autocomplete-bibtex\node_modules\sugar\release\sugar-full.development.js:6125:12)
    at C:\Users\tva\.atom\packages\autocomplete-bibtex\node_modules\sugar\release\sugar-full.development.js:179:25
    at Array.map (native)
    at Array.<anonymous> (C:\Users\tva\.atom\packages\autocomplete-bibtex\node_modules\sugar\release\sugar-full.development.js:180:23)
    at C:\Users\tva\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\babel-core\lib\traversal\scope\index.js:1136:132
    at Object.<anonymous> (C:\Users\tva\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\babel-core\lib\traversal\scope\index.js:1149:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\tva\AppData\Local\atom\app-1.0.3\resources\app.asar\src\babel.js:162:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.9
atom-ternjs, v0.7.1
autocomplete-bibtex, v0.5.7
autocomplete-hack, v1.0.1
autocomplete-python, v0.5.3
language-liquid, v0.4.0
linter, v1.2.4
linter-csslint, v0.0.14
linter-jscs, v2.0.4
linter-less, v2.0.3
linter-php, v1.0.2
linter-pylint, v0.2.2
minimap, v4.12.1

# Dev
No dev packages
```

**Comment by apcshields** [comment]
@tvanantwerp,

v0.6.0, released today, is expected to fix this issue. Could you please update and test?

Thanks!
Andrew

**Comment by tvanantwerp** [comment]
Confirmed that the error no longer occurs after upgrade to v0.6.0.
