### ISSUE TITLE
Failed to activate the autocomplete-bibtex package

### ISSUE THREAD

**Issue by apc** [apcshields/autocomplete-bibtex#77]
I'm getting this error as soon as I open Atom. The file does exist. Replacing the tilde with the full path does the trick, though. Is this the intended behavior? 

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package 0.7.0

### Stack Trace

Failed to activate the autocomplete-bibtex package

```
At ENOENT: no such file or directory, stat '~/Library/texmf/bibtex/bib/master/apcmaster.bib'

Error: ENOENT: no such file or directory, stat '~/Library/texmf/bibtex/bib/master/apcmaster.bib'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at Object.activate (/packages/autocomplete-bibtex/lib/main.coffee:34:20)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
     -0:08.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-spacegray-dark-neue-syntax.theme-spacegray-dark-neue-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
autocomplete-bibtex 0.7.0 
base16-ocean-dark-spacegray 0.13.0 
file-icons 2.1.3 
hey-pane 0.2.2 
language-latex 1.0.0 
latex 0.43.0 
latexer 0.3.0 
markdown-deluxe 1.0.0 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
minimap 4.27.1 
minimap-autohide 0.10.1 
open-recent 5.0.0 
organized 0.6.6 
pdf-view 0.57.0 
project-manager 3.3.4 
solarized-dark-ui 0.3.2 
spacegray-dark-neue-syntax 1.4.2 
spacegray-dark-neue-ui 1.7.1 
spacegray-dark-ui 0.12.0 
sync-settings 0.8.1 
tasks 2.6.6 
todo-show 1.11.0 
typewriter 0.6.0 
vim-mode-plus 0.89.0 
Zen 0.16.4 
```

**Comment by scoavoux** [comment]
I am having the same problem. It seems like `~` and `$HOME` are not developed. Is there a workaround? It is an important feature when we use package `sync-settings` to sync between computers with different usernames.

**Comment by adamaltmejd** [comment]
Same here! Did anyone find a workaround?

**Comment by mangecoeur** [comment]
Latest version should support `~` in file paths using whatever default behaviour is for your os, via `untildify` (so if it doesn't work, blame them >_<)
