### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by nickynicolson** [apcshields/autocomplete-bibtex#78]
[Enter steps to reproduce:]

1. Try to type an entry into the bibtex field in the autocomplete-bibtex settings pane in atom. 

Error is thrown on any keypress.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package 0.7.0

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:992

TypeError: path must be a string or Buffer
    at TypeError (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at ReferenceProvider.module.exports.ReferenceProvider.readReferenceFiles (/packages/autocomplete-bibtex/lib/provider.coffee:189:13)
    at ReferenceProvider.readReferenceFiles (/packages/autocomplete-bibtex/lib/provider.coffee:1:1)
    at ReferenceProvider.module.exports.ReferenceProvider.updateReferences (/packages/autocomplete-bibtex/lib/provider.coffee:164:20)
    at ReferenceProvider.updateReferences (/packages/autocomplete-bibtex/lib/provider.coffee:1:1)
    at /packages/autocomplete-bibtex/lib/provider.coffee:54:8
    at /app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at Config.module.exports.Config.emitChangeEvent (/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/app.asar/src/config.js:227:14)
    at SettingsPanel.set (/app.asar/node_modules/settings-view/lib/settings-panel.js:225:21)
    at /app.asar/node_modules/settings-view/lib/settings-panel.js:307:18
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:1392:25
```

### Commands

```
     -3:36.9.0 editor:newline (input.hidden-input)
  9x -3:26.7.0 core:backspace (input.hidden-input)
     -2:04.1.0 core:move-left (input.hidden-input)
     -1:55.9.0 core:move-right (input.hidden-input)
     -1:55.4.0 core:backspace (input.hidden-input)
  2x -1:54.9.0 core:move-left (input.hidden-input)
     -1:53.3.0 core:backspace (input.hidden-input)
  2x -1:37.7.0 core:select-right (input.hidden-input)
     -1:37 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
atom-mermaid 3.0.0 
autocomplete-bibtex 0.7.0 
autocomplete-python 1.8.62 
browser-plus 0.0.87 
browser-plus-zoom 0.0.2 
git-plus 7.3.3 
language-latexsimple 0.12.1 
language-sparql 0.3.0 
markdown-preview-enhanced 0.10.10 
markdown-preview-plus 2.4.9 
markdown-scroll-sync 2.1.2 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
tablr 1.8.1 
terminal-plus 0.14.5 
vim-mode-plus 0.84.1 
windows-context-menu 0.3.1 
wordcount 2.10.4 
Zen 0.16.4 
```

**Comment by mangecoeur** [comment]
could not reproduce, additional guards in 0.7.1 should fix this anyway
