### ISSUE TITLE
Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

### ISSUE THREAD

**Issue by werthen** [apcshields/autocomplete-bibtex#88]
1. Use atom 1.23.0-beta0

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package 0.7.1

### Stack Trace

Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/superstring/index.js:221

Error: PCRE does not support \L, \l, \N{name}, \U, or \u
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:221:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1147:32)
    at Cursor.getBeginningOfCurrentWordBufferPosition (/Applications/Atom Beta.app/Contents/Resources/app/src/cursor.js:523:45)
    at ReferenceProvider.module.exports.ReferenceProvider.getPrefix (/packages/autocomplete-bibtex/lib/provider.coffee:110:20)
    at ReferenceProvider.module.exports.ReferenceProvider.getSuggestions (/packages/autocomplete-bibtex/lib/provider.coffee:63:15)
    at ReferenceProvider.getSuggestions (/packages/autocomplete-bibtex/lib/provider.coffee:1:1)
    at providers.forEach.provider (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:279:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:21)
    at AutocompleteManager.findSuggestions (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:247:23)
```

### Commands

```
     -0:57.8.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:56.2.0 core:confirm (input.hidden-input)
     -0:51 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -0:49.3.0 zen:toggle (input.hidden-input)
     -0:49.3.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-genesis-syntax.theme-pristine-ui)
  6x -0:04.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
apex-ui 1.0.2 
apex-ui-slim 0.0.0 
ariake-dark-syntax 0.1.3 
atom-alignment 0.13.0 
atom-beautify 0.30.6 
atom-django 0.3.2 
atom-ide-ui 0.5.4 
atom-material-syntax 1.0.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-typescript 11.0.10 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-bibtex 0.7.1 
autocomplete-java 1.2.7 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.3 
build 0.69.0 
build-make 0.13.0 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
custom-title 1.0.1 
dash-syntax 0.4.1 
dash-ui 0.4.4 
django-templates 0.5.0 
docblockr 0.13.2 
editorconfig 2.2.2 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.13 
file-types 0.5.5 
firewatch-syntax 1.1.1 
flatwhite-syntax 0.8.1 
galaxy-syntax 1.1.0 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
gherkin-autocomplete 2.0.0 
gherkin-snippets 0.3.0 
github-atom-light-syntax 0.5.0 
gl-light-syntax 3.0.0 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 2.0.1 
ide-haskell 2.2.0 
ide-haskell-repl 0.7.4 
indent-guide-improved 1.4.13 
inspired-github 0.10.0 
intentions 1.1.5 
jshint 1.8.6 
language-crystal-actual 0.36.0 
language-docker 1.1.8 
language-elixir 0.20.3 
language-gherkin 1.0.4 
language-gitignore 0.3.0 
language-gradle 0.0.3 
language-groovy 0.7.0 
language-haskell 1.14.3 
language-latex 1.1.1 
language-markdown 0.25.1 
language-matlab 0.2.1 
language-nginx 0.8.0 
language-rust 0.4.12 
language-slim 1.0.0 
latex 0.49.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-javac 1.9.4 
linter-matlab 1.1.0 
linter-pylama 0.9.4 
linter-rubocop 2.2.0 
linter-rust 0.8.1 
linter-scss-lint 3.1.1 
linter-spell 0.15.0 
linter-spell-latex 0.10.0 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
loved-syntax 1.0.2 
markdown-preview-enhanced 0.15.0 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
min-ui 0.0.4 
neon-syntax 0.3.7 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-light-atom-syntax 2.1.0 
northem-light-atom-ui 2.1.1 
omnisharp-atom 0.31.2 
overwatch-light-syntax 0.4.0 
parinfer 1.20.0 
pdf-view 0.59.0 
pen-paper-coffee-syntax 0.14.9 
piatto-light 2.0.2 
pigments 0.40.2 
pristine-ui 1.1.10 
pure-syntax 0.3.0 
python-tools 0.6.9 
quantum-syntax 0.3.0 
quantum-ui 0.3.0 
ruby-block 0.3.6 
script 3.17.3 
set-syntax 0.4.0 
spacegray-eighties-ui 2.0.0 
subway-seoul 2.0.2 
tablr 1.8.3 
two-light-ui 1.1.3 
vim-mode-plus 1.17.0 
wordcount 2.10.4 
Zen 0.18.0 
zentabs 0.8.8 
```

**Comment by dbobak** [comment]
The same in Windows:

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package 0.7.1


### Stack Trace

Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

```
At C:\Users\deni\AppData\Local\atom\app-1.22.0-beta0\resources\app.asar\node_modules\superstring\index.js:221

Error: PCRE does not support \L, \l, \N{name}, \U, or \u
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:221:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1147:32)
    at Cursor.getBeginningOfCurrentWordBufferPosition (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/src/cursor.js:523:45)
    at ReferenceProvider.module.exports.ReferenceProvider.getPrefix (/packages/autocomplete-bibtex/lib/provider.coffee:110:20)
    at ReferenceProvider.module.exports.ReferenceProvider.getSuggestions (/packages/autocomplete-bibtex/lib/provider.coffee:63:15)
    at ReferenceProvider.getSuggestions (/packages/autocomplete-bibtex/lib/provider.coffee:1:1)
    at providers.forEach.provider (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:279:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:21)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.23.0-beta0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:247:23)
```

### Commands

```
```

### Non-Core Packages

```
academic 0.34.1 
advanced-open-file 0.16.7 
atom-beautify 0.30.6 
atom-codesearch 1.2.0 
atom-fuzzy-grep 0.16.0 (disabled)
atomic-emacs 0.12.1 (disabled)
autocomplete-bibtex 0.7.1 
autocomplete-paths 2.12.1 
build 0.69.0 (disabled)
busy 0.7.0 
busy-signal 1.4.3 
copy-path 0.4.2 
document-outline 1.6.17 (disabled)
file-icons 2.1.13 
file-types 0.5.5 
highlight-selected 0.13.1 
intentions 1.1.5 
language-batchfile 0.7.0 
language-latex 1.1.1 
language-pfm 0.82.0 
language-pgsql 0.2.3 
latex 0.49.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-markdown 5.2.0 
linter-ui-default 1.6.10 
markdown-preview-enhanced 0.15.0 
markdown-writer 2.7.3 
open-recent 5.0.0 
pandoc 0.2.2 (disabled)
pandoc-convert 1.1.1 (disabled)
pen-paper-coffee-syntax 0.14.9 
preview-inline 1.4.7 
project-manager 3.3.5 
symbol-gen 1.3.1 
sync-settings 0.8.3 
tasks 2.6.7 
tidy-markdown 3.0.1 (disabled)
todo-show 2.1.0 
wordcount 2.10.4 
wrap-with-anything 0.1.1 
zotero-citations 0.19.1 (disabled)
zotero-picker 1.5.0 (disabled)
```

**Comment by mangecoeur** [comment]
looks like its an issue with xregx, if you can try the latest version from master to test would be helpful.

**Comment by werthen** [comment]
The following error occurs when using the master version:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-beta0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package 0.7.1


### Stack Trace

Failed to load the autocomplete-bibtex package

```
At Cannot find module 'zotero-bibtex-parse/zotero-bibtex-parse'

Error: Cannot find module 'zotero-bibtex-parse/zotero-bibtex-parse'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-bibtex/lib/bibtex-reader.js:11:21)
    at /packages/autocomplete-bibtex/lib/bibtex-reader.js:13:34)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-bibtex/lib/provider.js:8:22)
    at /packages/autocomplete-bibtex/lib/provider.js:336:2)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-bibtex/lib/main.js:10:27)
    at /packages/autocomplete-bibtex/lib/main.js:113:3)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
  2x -0:06.6.0 datatip:toggle (input.hidden-input)
```

### Non-Core Packages

```
apex-ui 1.0.2 
apex-ui-slim 0.0.0 
ariake-dark-syntax 0.1.3 
atom-alignment 0.13.0 
atom-beautify 0.30.6 
atom-django 0.3.2 
atom-ide-ui 0.5.4 
atom-material-syntax 1.0.7 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-typescript 11.0.10 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-bibtex 0.7.1 
autocomplete-java 1.2.7 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.3 
build 0.69.0 
build-make 0.13.0 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
custom-title 1.0.1 
dash-syntax 0.4.1 
dash-ui 0.4.4 
django-templates 0.5.0 
docblockr 0.13.2 
editorconfig 2.2.2 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.13 
file-types 0.5.5 
firewatch-syntax 1.1.1 
flatwhite-syntax 0.8.1 
galaxy-syntax 1.1.0 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
gherkin-autocomplete 2.0.0 
gherkin-snippets 0.3.0 
github-atom-light-syntax 0.5.0 
gl-light-syntax 3.0.0 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 2.0.1 
ide-haskell 2.2.0 
ide-haskell-repl 0.7.4 
indent-guide-improved 1.4.13 
inspired-github 0.10.0 
intentions 1.1.5 
jshint 1.8.6 
language-crystal-actual 0.36.0 
language-docker 1.1.8 
language-elixir 0.20.3 
language-gherkin 1.0.4 
language-gitignore 0.3.0 
language-gradle 0.0.3 
language-groovy 0.7.0 
language-haskell 1.14.3 
language-latex 1.1.1 
language-markdown 0.25.1 
language-matlab 0.2.1 
language-nginx 0.8.0 
language-rust 0.4.12 
language-slim 1.0.0 
latex 0.49.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-javac 1.9.4 
linter-matlab 1.1.0 
linter-pylama 0.9.4 
linter-rubocop 2.2.0 
linter-rust 0.8.1 
linter-scss-lint 3.1.1 
linter-spell 0.15.0 
linter-spell-latex 0.10.0 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
loved-syntax 1.0.2 
markdown-preview-enhanced 0.15.0 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
min-ui 0.0.4 
neon-syntax 0.3.7 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
northem-light-atom-syntax 2.1.0 
northem-light-atom-ui 2.1.1 
omnisharp-atom 0.31.2 
overwatch-light-syntax 0.4.0 
parinfer 1.20.0 
pdf-view 0.59.0 
pen-paper-coffee-syntax 0.14.9 
piatto-light 2.0.2 
pigments 0.40.2 
pristine-ui 1.1.10 
pure-syntax 0.3.0 
python-tools 0.6.9 
quantum-syntax 0.3.0 
quantum-ui 0.3.0 
ruby-block 0.3.6 
script 3.17.3 
set-syntax 0.4.0 
spacegray-eighties-ui 2.0.0 
subway-seoul 2.0.2 
tablr 1.8.3 
two-light-ui 1.1.3 
vim-mode-plus 1.17.0 
wordcount 2.10.4 
Zen 0.18.0 
zentabs 0.8.8 
```

**Comment by mangecoeur** [comment]
@werthen ok was just an issue beteen dev mode and release mode. Latest commit should fix this I think.

**Comment by werthen** [comment]
I'm not encountering any issue with the latest commit!
