### ISSUE TITLE
error when opening Atom

### ISSUE THREAD

**Issue by mkborregaard** [apcshields/autocomplete-bibtex#92]
I've suddenly started getting an error every time I open Atom:
```
Unexpected token r in JSON at position 8928 in /Users/michael/.atom/packages/autocomplete-bibtex/package.json
Hide Stack Trace
SyntaxError: Unexpected token r in JSON at position 8928
    at JSON.parse (<anonymous>)
    at parseObject (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:58:25)
    at parseContentsSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:72:22)
    at Object.readFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:184:20)
    at PackageManager.loadPackageMetadata (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:843:33)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:586:29)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:530:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:528:23)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:821:34
  at /Users/michael/.atom/packages/autocomplete-bibtex/package.json:1:1
```

**Comment by mangecoeur** [comment]
could not reproduce, might be an error in your citation files or config
