### ISSUE TITLE
Uncaught TypeError: Token mismatch: match

### ISSUE THREAD

**Issue by saltyPhysics** [apcshields/autocomplete-bibtex#93]
Hi Im trying to get the autocomplete to work but can't seem to read in the bib file.
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [autocomplete-bibtex](https://github.com/apcshields/autocomplete-bibtex) package 1.1.0

### Stack Trace

Uncaught TypeError: Token mismatch: match

```
At /Users/manishdevana/.atom/packages/autocomplete-bibtex/lib/lite-bibtex-parse.js:220

TypeError: Token mismatch: match
    at BibtexParser.match (/packages/autocomplete-bibtex/lib/lite-bibtex-parse.js:220:13)
    at BibtexParser.parse (/packages/autocomplete-bibtex/lib/lite-bibtex-parse.js:512:12)
    at Object.toJSON (/packages/autocomplete-bibtex/lib/lite-bibtex-parse.js:521:5)
    at BibtexReader.read (/packages/autocomplete-bibtex/lib/bibtex-reader.js:16:32)
    at ReferenceProvider.readReferenceFile (/packages/autocomplete-bibtex/lib/provider.js:128:19)
    at ReferenceProvider.readReferenceFiles (/packages/autocomplete-bibtex/lib/provider.js:114:45)
    at ReferenceProvider.update (/packages/autocomplete-bibtex/lib/provider.js:78:28)
    at /packages/autocomplete-bibtex/lib/provider.js:62:14
    at /Applications/Atom 2.app/Contents/Resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom 2.app/Contents/Resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom 2.app/Contents/Resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/Applications/Atom 2.app/Contents/Resources/app/src/config.js:248:20)
    at SettingsPanel.set (/Applications/Atom 2.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at /Applications/Atom 2.app/Contents/Resources/app/node_modules/settings-view/lib/settings-panel.js:315:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom 2.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/Applications/Atom 2.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1699:26)
    at later (/Applications/Atom 2.app/Contents/Resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -7:14 markdown-writer:insert-new-line (input.hidden-input)
     -7:13.9.0 editor:newline (input.hidden-input)
 13x -7:03.2.0 core:backspace (input.hidden-input)
     -5:43.7.0 autocomplete-clang:toggle (input.hidden-input)
  4x -5:41.2.0 core:backspace (input.hidden-input)
  5x -5:35.2.0 core:undo (input.hidden-input)
     -5:28.5.0 autocomplete-clang:toggle (input.hidden-input)
  9x -3:30.3.0 core:backspace (input.hidden-input)
     -0:49.9.0 core:move-left (input.hidden-input)
  4x -0:18.1.0 core:backspace (input.hidden-input)
     -0:06.5.0 core:move-left (input.hidden-input)
     -0:05.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-html-preview 0.2.5 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.6 
atom-terminal 0.8.0 
atom-terminal-panel 4.4.4 
autocomplete-bibtex 1.1.0 
autocomplete-clang 0.11.4 
build 0.70.0 
busy-signal 1.4.3 
city-lights-ui 1.3.1 
file-icons 2.1.15 
hydrogen-launcher 1.2.1 
intentions 1.1.5 
language-ini 1.19.0 
latexer 0.3.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
markdown-writer 2.7.3 
night-syntax 0.2.7 
night-terminal 1.1.1 
night-ui 0.1.3 
northem-dark-atom-syntax 2.1.0 
northem-dark-atom-ui 2.1.0 
platformio-ide 2.0.0-rc.5 
platformio-ide-debugger 1.2.5 
platformio-ide-terminal 2.7.0 
script 3.17.3 
tool-bar 1.1.0 
wordcount 2.10.4 
```

**Comment by mangecoeur** [comment]
hopefully this is working for you know, although I plan to have better error messages with the bibtex has errors in it
